name: my_first_workflow

on:
  push:
    branches:
    - main	
  pull_request:
    branches:	
    - main
  workflow_dispatch:



jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: trial_checkout
      run: echo "hello World"
      shell: bash
  goodbye:
    runs-on: ubuntu-latest
    steps:
    - name: goodbye_rohith
      run: echo "good bye world"
      shell: bash
